cart/urls.py
from django.urls import path

from cart.views import *

urlpatterns = [
    path('cart/', cart, name='cart'),
    path('add_cart/<int:id>/', add_cart, name='add_cart'),
    path('add_goods/<int:id>/', add_goods, name='add_goods'),
    path('minus_goods/<int:id>/', minus_goods, name='minus_goods'),
    path('del_goods/<int:id>/', del_goods, name='del_goods'),
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from dailyfresh.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('goods/', include(('goods.urls', 'goods'), namespace='goods')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods.views import *

urlpatterns = [
    path('index/', index, name='index'),
    path('detail/<int:id>/', detail, name='detail'),
    path('goods_list/<int:id>/', goods_list, name='goods_list'),
    path('search/<keywords>/', search, name='search'),
]

order/urls.py
from django.urls import path

from order.views import *

urlpatterns = [
    path('order/', order, name='order'),
]

user/urls.py
from django.urls import path

from user.views import *

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('is_login/', is_login, name='is_login'),
    path('user_center_info/', user_center_info, name='user_center_info'),
    path('user_center_order/', user_center_order, name='user_center_order'),
    path('user_center_site/', user_center_site, name='user_center_site'),
    path('add_site/', add_site, name='add_site'),
]

cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

goods/models.py
from django.db import models


class GoodsCategory(models.Model):
    """
    Goods类别
    """
    CATEGORY_TYPE = (
        (1, '新鲜水果'),
        (2, '海鲜水产'),
        (3, '猪牛羊肉'),
        (4, '禽类蛋品'),
        (5, '新鲜蔬菜'),
        (6, '速冻食品'),
    )
    category_type = models.IntegerField(choices=CATEGORY_TYPE, verbose_name='类目级别')
    category_front_image = models.ImageField(upload_to='goods/images/', null=True, blank=True, verbose_name='封面图')

    class Meta:
        db_table = 'f_goods_category'


class Goods(models.Model):
    """
    商品
    """
    category = models.ForeignKey(GoodsCategory, verbose_name='商品类目', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='商品名')
    goods_sn = models.CharField(max_length=50, default='', verbose_name='商品唯一货号')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    sold_nums = models.IntegerField(default=0, verbose_name='销售量')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏数')
    goods_nums = models.IntegerField(default=0, verbose_name='商品库存')
    market_price = models.FloatField(default=0, verbose_name='市场价格')
    shop_price = models.FloatField(default=0, verbose_name='本店价格')
    goods_brief = models.CharField(max_length=500, verbose_name='商品简短描述')
    goods_desc = models.TextField(null=True)
    ship_free = models.BooleanField(default=True, verbose_name='是否承担运费')
    goods_front_image = models.ImageField(upload_to='goods/images/', null=True, blank=True, verbose_name='封面图')
    is_new = models.BooleanField(default=False, verbose_name='是否新品')
    is_hot = models.BooleanField(default=False, verbose_name='是否热销')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        db_table = 'f_goods'

cart/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from cart.models import ShoppingCart
from goods.models import Goods


def cart(request):
    if request.method == 'GET':
        goods = Goods.objects.all()
        user_id = request.session.get('user_id')
        # 未登录时，从session取数据
        if not user_id:
            goods_sessions = request.session.get('goods')
            response = {'goods_sessions': goods_sessions, 'goods': goods}
            return render(request, 'cart.html', response)
        # 登录时从数据库取数据
        cart_goods = ShoppingCart.objects.all()
        cgood_list = []
        for good in cart_goods:
            goods_id = good.goods_id
            num = good.nums
            is_select = good.is_select
            cgood = [goods_id, num, is_select, user_id]
            cgood_list.append(cgood)
        response = {'goods_sessions': cgood_list, 'goods': goods}
        return render(request, 'cart.html', response)


def add_cart(request, id):
    res = HttpResponseRedirect(reverse('goods:detail', args=(id,)))
    if request.method == 'GET':
        return res
    if request.method == 'POST':
        goods_id = id
        num = request.POST.get('num', '1')
        is_select = '0'
        goods = [goods_id, num, is_select]
        user_id = request.session.get('user_id')
        goods_init = request.session.get('goods')
        # 没有登陆时
        if not user_id:
            # 购物车有东西时
            if goods_init:
                for good in goods_init:
                    # 购物车中存在此商品时
                    if id == good[0]:
                        good[1] = str(int(good[1]) + int(goods[1]))
                        request.session['goods'] = goods_init
                        return res
                # 购物车中不存在此商品时
                goods_init.append(goods)
                request.session['goods'] = goods_init
                return res
            # 购物车没东西时
            request.session['goods'] = [goods]
            return res
        # 登录时
        cgoods = ShoppingCart.objects.all()
        goods_list = []
        for cgood in cgoods:
            goods_id = cgood.goods_id
            num = cgood.nums
            is_select = cgood.is_select
            allgoods = [goods_id, num, is_select, user_id]
            goods_list.append(allgoods)
        for good in goods_list:
            # 购物车中存在此商品时
            if goods[0] == good[0]:
                good[1] = str(int(good[1]) + int(goods[1]))
                ShoppingCart.objects.filter(goods_id=good[0]).update(nums=good[1])
                return res
        # 购物车中不存在此商品时
        sgood = ShoppingCart()
        sgood.goods_id = goods[0]
        sgood.nums = goods[1]
        sgood.is_select = goods[2]
        sgood.user_id = user_id
        sgood.save()
        return res


def add_goods(request, id):
    if request.is_ajax():
        user_id = request.session.get('user_id')
        goods = request.session.get('goods')
        if not user_id:
            for good in goods:
                if id == good[0]:
                    good[1] = str(int(good[1]) + 1)
                    request.session['goods'] = goods
                    return JsonResponse({'data': good[1]})
        cart_goods = ShoppingCart.objects.all()
        for cgood in cart_goods:
            if id == cgood.goods_id:
                num = ShoppingCart.objects.filter(goods_id=id).first().nums + 1
                ShoppingCart.objects.filter(goods_id=id).update(nums=num)
                return JsonResponse({'data': str(num)})


def minus_goods(request, id):
    if request.is_ajax():
        user_id = request.session.get('user_id')
        goods = request.session.get('goods')
        if not user_id:
            for good in goods:
                if id == good[0]:
                    if int(good[1]) == 1:
                        goods.remove(good)
                        request.session['goods'] = goods
                        return JsonResponse({'data': ''})
                    good[1] = str(int(good[1]) - 1)
                    request.session['goods'] = goods
                    return JsonResponse({'data': good[1]})
        cart_goods = ShoppingCart.objects.all()
        for cgood in cart_goods:
            if id == cgood.goods_id:
                if cgood.nums == 1:
                    cgood.delete()
                    return JsonResponse({'data': ''})
                num = ShoppingCart.objects.filter(goods_id=id).first().nums - 1
                ShoppingCart.objects.filter(goods_id=id).update(nums=num)
                return JsonResponse({'data': str(num)})


def del_goods(request, id):
    if request.is_ajax():
        user_id = request.session.get('user_id')
        goods = request.session.get('goods')
        if not user_id:
            for good in goods:
                if id == good[0]:
                    goods.remove(good)
                    request.session['goods'] = goods
                    return JsonResponse({'data': ''})
        cart_goods = ShoppingCart.objects.all()
        for cgood in cart_goods:
            if id == cgood.goods_id:
                cgood.delete()
                return JsonResponse({'data': ''})

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {% block title %}
    {% endblock %}

    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block body %}
{% endblock %}

{% block footer %}
{% endblock %}

{% block bottom_js %}
{% endblock %}

</body>
</html>

templates/base_main.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{% endblock %}

{% block header %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                <div class="login_btn fl">
                </div>
                <script>
                    $.ajax({
                        type: 'GET',
                        url: '/user/is_login/',
                        async: true,
                        success: function (data) {
                            if (data['username']) {
                                var html1 = "<a>欢迎您：" + data['username'] + "</a>\n" +
                                    "<span>|</span>\n" +
                                    "<a href=\"{% url 'user:logout' %}\">退出</a>";
                                $('.login_btn').append(html1)
                            } else {
                                var html2 = "<a href=\"{% url 'user:login' %}\">登录</a>\n" +
                                    "<span>|</span>\n" +
                                    "<a href=\"{% url 'user:register' %}\">注册</a>";
                                $('.login_btn').append(html2)
                            }
                        },
                        error: function () {
                            alert('获取数据失败！');
                        }
                    })
                </script>

                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user_center_info' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'order:order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}
    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
{% endblock %}

templates/detail.html
{% extends 'base_main.html' %}

{% block title %}
    <title>天天生鲜-商品详情</title>
{% endblock %}

{% block body %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="search_con fl">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">1</div>
        </div>
    </div>

    <script>
        $('.input_btn').click(function () {
            var keywords = $('.input_text').val();
            $.ajax({
                type: 'post',
                url: '/goods/search/' + keywords + '/',
                async: true,
                data: {'keywords': keywords},
                success: function (data) {
                    if (data['url'] == '') {
                        alert('没这个东西')
                    } else {
                        window.location.href = data['url']
                    }
                },
                error: function () {
                    alert('请输入要所搜的商品')
                }
            })
        })
    </script>

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    <li><a href="{% url 'goods:goods_list' id=1 %}" class="fruit">新鲜水果</a></li>
                    <li><a href="{% url 'goods:goods_list' id=2 %}" class="seafood">海鲜水产</a></li>
                    <li><a href="{% url 'goods:goods_list' id=3 %}" class="meet">猪牛羊肉</a></li>
                    <li><a href="{% url 'goods:goods_list' id=4 %}" class="egg">禽类蛋品</a></li>
                    <li><a href="{% url 'goods:goods_list' id=5 %}" class="vegetables">新鲜蔬菜</a></li>
                    <li><a href="{% url 'goods:goods_list' id=6 %}" class="ice">速冻食品</a></li>
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="{% url 'goods:index' %}">全部分类</a>
        <span>></span>
        <a href="#">{{ category.get_category_type_display }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <form action="{% url 'cart:add_cart' id=good.id %}" method="post">
        <div class="goods_detail_con clearfix">
            <img class="goods_detail_pic fl" src="/media/{{ good.goods_front_image }}">

            <div class="goods_detail_list fr">
                <h3>{{ good.name }}</h3>
                <p>{{ good.goods_brief }}</p>
                <div class="prize_bar">
                    <span class="show_pirze">¥<em>{{ good.shop_price }}</em></span>
                    <span class="show_unit">单  位：500g</span>
                </div>
                <div class="goods_num clearfix">
                    <div class="num_name fl">数 量：</div>
                    <div class="num_add fl">
                        <input type="text" class="num_show fl" name="num" value="1">
                        <a class="add fr" style="cursor: pointer">+</a>
                        <a class="minus fr" style="cursor: pointer">-</a>
                    </div>
                </div>
                <div class="total">总价：<em>{{ good.shop_price }}元</em></div>
                <div class="operate_btn">
                    <a href="javascript:;" class="buy_btn">立即购买</a>
                    <button type="submit" class="add_cart" id="add_cart" style="cursor: pointer">加入购物车</button>
                </div>
            </div>
        </div>
    </form>

    <script>
        $('.add').click(function () {
            var num = Number($('.num_add>input').val());
            $('.num_add>input').val(num + 1);
            num = $('.num_add>input').val();
            total = parseInt(num) * parseInt({{ good.shop_price }});
            $('.total>em').empty();
            $('.total>em').prepend(total + ".0元")
        });
        $('.minus').click(function () {
            var num = Number($('.num_add>input').val());
            if (num <= 1) {
                $('.num_add>input').val(1);
            } else {
                $('.num_add>input').val(num - 1);
                num = $('.num_add>input').val();
                total = parseInt(num) * parseInt({{ good.shop_price }});
                $('.total>em').empty();
                $('.total>em').prepend(total + ".0元")
            }
        })
    </script>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    <li>
                        <a href="#"><img src="/static/images/goods/goods001.jpg"></a>
                        <h4><a href="#">进口柠檬</a></h4>
                        <div class="prize">￥3.90</div>
                    </li>
                    <li>
                        <a href="#"><img src="/static/images/goods/goods002.jpg"></a>
                        <h4><a href="#">玫瑰香葡萄</a></h4>
                        <div class="prize">￥16.80</div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>
            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村
                        ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。
                    </dd>
                </dl>
            </div>
        </div>
    </div>
{% endblock %}

{% block bottom_js %}
    <div class="add_jump"></div>

    <script type="text/javascript" src="/static/js/jquery-1.12.2.js"></script>
    <script type="text/javascript">
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
        $('#add_cart').click(function () {
            $(".add_jump").stop().animate({
                    'left': $to_y + 7,
                    'top': $to_x + 7
                },
                "fast", function () {
                    $(".add_jump").fadeOut('fast', function () {
                        $('#show_count').html(2);
                    });
                });
        })
    </script>
{% endblock %}

templates/index.html
{% extends 'base_main.html' %}

{% block title %}
    <title>天天生鲜-首页</title>
{% endblock %}

{% block js %}
    {#    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>#}
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}

{% block body %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="search_con fl">
            <input type="text" class="input_text fl" name="keywords" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">1</div>
        </div>
    </div>

    <script>
        $('.input_btn').click(function () {
            var keywords = $('.input_text').val();
            $.ajax({
                type: 'post',
                url: '/goods/search/' + keywords + '/',
                async: true,
                data: {'keywords': keywords},
                success: function (data) {
                    if (data['url'] == '') {
                        alert('没这个东西')
                    } else {
                        window.location.href = data['url']
                    }
                },
                error: function () {
                    alert('请输入要所搜的商品')
                }
            })
        })
    </script>

    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            <li><a href="#1" class="fruit">新鲜水果</a></li>
            <li><a href="#2" class="seafood">海鲜水产</a></li>
            <li><a href="#3" class="meet">猪牛羊肉</a></li>
            <li><a href="#4" class="egg">禽类蛋品</a></li>
            <li><a href="#5" class="vegetables">新鲜蔬菜</a></li>
            <li><a href="#6" class="ice">速冻食品</a></li>
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                <li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            <a href="#"><img src="/static/images/adv01.jpg"></a>
            <a href="#"><img src="/static/images/adv02.jpg"></a>
        </div>
    </div>
    {% load filter_get %}
    {% for gc in goods_category %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="{{ gc.category_type }}">{{ gc.get_category_type_display }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for good in goods|filter_get:gc.id|slice:":3" %}
                        <a href="{% url 'goods:detail' id=good.id %}">{{ good.name }}</a>
                    {% endfor %}
                </div>
                <a href="{% url 'goods:goods_list' id=gc.id %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="/media/{{ gc.category_front_image }}"></div>
                <ul class="goods_list fl">
                    {% for good in goods|filter_get:gc.id|slice:"0:4" %}
                        <li>
                            <h4><a href="{% url 'goods:detail' id=good.id %}">{{ good.name }}</a></h4>
                            <a href="{% url 'goods:detail' id=good.id %}"><img
                                    src="/media/{{ good.goods_front_image }}"></a>
                            <div class="prize">¥ {{ good.shop_price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block bottom_js %}
    {#    <script type="text/javascript" src="/static/js/slideshow.js"></script>#}
    <script type="text/javascript">
        BCSlideshow('focuspic');
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '2';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        }
    </script>
{% endblock %}

templates/login.html
{% extends 'base_main.html' %}

{% block title %}
    <title>天天生鲜-登录</title>
{% endblock %}

{% block header %}
{% endblock %}

{% block body %}
    <div class="login_top clearfix">
        <a href="{% url 'goods:index' %}" class="login_logo"><img src="/static/images/logo02.png"></a>
    </div>
    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'user:register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    <form action="" method="post">
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名">
                        <p style="width: 50px; height: 35px; color: red">{{ errors.username }}</p>
                        <div class="user_error">输入错误</div>
                        <input type="password" name="password" class="pass_input" placeholder="请输入密码">
                        <p style="width: 50px; height: 40px; color: red">{{ errors.password }}</p>
                        <div class="pwd_error">输入错误</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="">
                            <label>记住用户名</label>
                            <a href="#">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user_center_site.html
{% extends 'base_main.html' %}

{% block title %}
    <title>天天生鲜-用户中心</title>
{% endblock %}

{% block body %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="search_con fr">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
    </div>

    <script>
        $('.input_btn').click(function () {
            var keywords = $('.input_text').val();
            $.ajax({
                type: 'post',
                url: '/goods/search/' + keywords + '/',
                async: true,
                data: {'keywords': keywords},
                success: function (data) {
                    if (data['url'] == '') {
                        alert('没这个东西')
                    } else {
                        window.location.href = data['url']
                    }
                },
                error: function () {
                    alert('请输入要所搜的商品')
                }
            })
        })
    </script>

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user_center_info' %}">· 个人信息</a></li>
                <li><a href="{% url 'user:user_center_order' %}">· 全部订单</a></li>
                <li><a href="{% url 'user:user_center_site' %}" class="active">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">收货地址</h3>
            <div class="site_con">
                {% for add in add_lsit %}
                    <dl>
                        <dd>{{ add.0 }} {{ add.1 }} {{ add.2 }} {{ add.3 }}（{{ add.4 }} 收） {{ add.5 }}</dd>
                    </dl>
                {% endfor %}
            </div>
            <h3 class="common_title2">编辑地址</h3>
            <div class="site_con">
                <form action="{% url 'user:add_site' %}" method="post">
                    <div class="form_group">
                        <label>收件人：</label>
                        <input type="text" name="receiver">
                    </div>
                    <div class="form_group">
                        <script src="/static/dist/distpicker.js"></script>
                        <label>地址：</label>
                        <div data-toggle="distpicker" id="target">
                            <select data-province="----选择省----" name="province"> </select>
                            <select data-city="----选择市----" name="city"> </select>
                            <select data-district="----选择区----" name="district"> </select>
                        </div>
                    </div>

                    <div class="form_group form_group2">
                        <label>详细地址：</label>
                        <textarea class="site_area" name="address"></textarea>
                    </div>
                    <div class="form_group">
                        <label>邮编：</label>
                        <input type="text" name="postcode">
                    </div>
                    <div class="form_group">
                        <label>手机：</label>
                        <input type="text" name="phone">
                    </div>
                    <script>
                        $('＃target').distpicker();
                    </script>
                    <input type="submit" name="" value="提交" class="info_submit">
                </form>
            </div>
        </div>
    </div>
{% endblock %}